import * as stylex from '@stylexjs/stylex';

/**
 * Local styles for the homepage entrance and the standalone guide.
 * Shared controls (buttons, panels, notices, fields, chips, steps, keycaps)
 * come from `ui`; everything here is specific to these two views.
 */
export const styles = stylex.create({
  /* ------------------------------------------------------------- homepage -- */

  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },

  hero: {
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderRadius: 0,
    backgroundColor: '#130e23',
    backgroundImage: 'var(--surface-leather)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
    boxShadow: 'var(--shadow)',
    /* The frame is foreground artwork, never a reason to inset the scene image. */
    '::before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      zIndex: 2,
      pointerEvents: 'none',
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'transparent',
      borderImageSource: 'var(--frame-panel)',
      borderImageSlice: 48,
      borderImageWidth: '26px',
      borderImageRepeat: 'stretch',
    },
    '::after': {
      content: '""',
      position: 'absolute',
      inset: 0,
      pointerEvents: 'none',
      backgroundImage:
        'linear-gradient(90deg,rgba(9,11,20,.52),rgba(9,11,20,.08)70%),linear-gradient(180deg,rgba(9,11,20,.08),rgba(9,11,20,.5)65%,transparent)',
    },
  },
  /** Feather the scene into the repeatable leather; no hard inner rectangle. */
  heroArt: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    objectPosition: 'center 34%',
    opacity: 0.65,
    maskImage: 'radial-gradient(ellipse 110% 85% at 50% 0%,#000 18%,transparent 95%)',
    pointerEvents: 'none',
  },
  heroLayout: {
    position: 'relative',
    zIndex: 1,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.7fr) minmax(280px, 1fr)',
    gap: 20,
    alignItems: 'start',
    padding: 'clamp(24px, 2.8vw, 36px)',
    '@media (max-width: 1000px)': {
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  heroMain: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  heroFacts: { gridColumn: '1 / -1', minWidth: 0 },
  crest: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  crestImg: {
    flex: 'none',
    borderRadius: '50%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(255, 215, 154, 0.34)',
    boxShadow: '0 0 20px rgba(150, 136, 255, 0.26)',
  },
  heroEyebrow: {
    fontSize: '.76rem',
    letterSpacing: '.22em',
    textTransform: 'uppercase',
    color: 'var(--gold)',
  },
  sigils: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginLeft: 'auto',
    opacity: 0.85,
  },
  sigilImg: {
    flex: 'none',
    filter: 'drop-shadow(0 0 9px rgba(150, 136, 255, 0.45))',
  },
  heroTitle: {
    margin: '6px 0 4px',
    fontSize: 'clamp(1.95rem, 4.4vw, 2.85rem)',
    lineHeight: 1.06,
    letterSpacing: '.12em',
    color: 'var(--ink)',
    textShadow: '0 0 34px rgba(150, 136, 255, 0.35)',
    '@supports (background-clip: text) or (-webkit-background-clip: text)': {
      background: 'linear-gradient(110deg, #fff 4%, var(--gold) 44%, var(--arcane) 100%)',
      backgroundClip: 'text',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
    },
  },
  heroLead: {
    margin: '0 0 20px',
    fontSize: 'clamp(0.96rem, 1.3vw, 1.06rem)',
    letterSpacing: '.04em',
    color: 'var(--ink-dim)',
  },
  facts: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(112px, 1fr))',
    gap: 1,
    padding: 4,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '12px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: 'var(--line)',
    overflow: 'hidden',
    '@media (max-width: 620px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  fact: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
    padding: '9px 14px',
    backgroundColor: '#131022',
    backgroundImage:
      'linear-gradient(180deg, rgba(122, 104, 255, 0.1), rgba(9, 7, 20, 0) 60%), var(--surface-stone)',
    backgroundSize: 'auto, 256px 256px',
    backgroundRepeat: 'no-repeat, repeat',
  },
  factValue: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'clamp(1.15rem, 2vw, 1.5rem)',
    fontVariantNumeric: 'tabular-nums',
    color: 'var(--gold)',
  },
  factLabel: {
    fontSize: '.74rem',
    letterSpacing: '.08em',
    color: 'var(--ink-faint)',
  },
  /** Notices inside the hero keep the card's rhythm instead of the shared bottom margin. */
  heroNotice: {
    marginTop: 0,
    marginBottom: 12,
  },
  h2Size: {
    fontSize: 'clamp(1.35rem, 2.6vw, 1.85rem)',
  },

  entries: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 12,
    '@media (max-width: 600px)': {
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  entry: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    minWidth: 0,
    padding: '18px 16px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '14px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: '#161226',
    backgroundImage:
      'linear-gradient(180deg, rgba(40, 30, 84, 0.38), rgba(12, 9, 26, 0.5)), var(--surface-vellum)',
    backgroundSize: 'auto, 256px 256px',
    backgroundRepeat: 'no-repeat, repeat',
  },
  entryQuick: {
    borderImageSource: 'var(--frame-accent)',
    boxShadow: '0 14px 34px rgba(56, 38, 132, 0.32)',
  },
  entryHead: {
    display: 'flex',
    alignItems: 'center',
    minHeight: 36,
    gap: 10,
    flexWrap: 'wrap',
  },
  entryTitle: {
    margin: 0,
    fontSize: '1.2rem',
    letterSpacing: '.06em',
    color: 'var(--ink)',
  },
  entryTag: {
    flex: 'none',
    padding: '3px 10px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-control)',
    borderImageSlice: 48,
    borderImageWidth: '10px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: '#1a142e',
    backgroundImage: 'var(--surface-stone)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
    fontSize: '.72rem',
    letterSpacing: '.1em',
    color: 'var(--gold)',
  },
  entryNote: {
    margin: 0,
    fontSize: '.86rem',
    color: 'var(--ink-dim)',
    minHeight: '3.3em',
  },
  entrySeats: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginTop: 0,
  },
  duelMark: {
    fontFamily: 'var(--font-display)',
    fontSize: '.7rem',
    color: 'var(--gold)',
    padding: '0 2px',
  },
  seatImg: {
    flex: 'none',
    width: 28,
    height: 28,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line-strong)',
    borderRadius: '50%',
    objectFit: 'cover',
    opacity: 0.85,
  },
  /** The two CTAs share one baseline, whatever each card's copy does above them. */
  entryButton: {
    width: '100%',
    marginTop: 'auto',
    minHeight: 48,
    padding: '10px 12px',
    fontSize: 'clamp(.88rem, 1.3vw, 1rem)',
    letterSpacing: '.02em',
  },

  /* --------------------------------------------------------- activity panel -- */

  activity: {
    margin: 0,
    padding: 'clamp(12px, 1.8vw, 18px)',
  },
  activityHead: {
    marginBottom: 8,
  },
  activityNote: {
    margin: '10px 0 0',
    fontSize: '.82rem',
    color: 'var(--ink-faint)',
  },
  activityNoteError: {
    color: '#ffd8de',
  },

  /* ------------------------------------------------------------ player card -- */

  aside: {
    alignSelf: 'stretch',
    minWidth: 0,
    padding: '20px 18px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '14px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: '#12101f',
    backgroundImage:
      'linear-gradient(180deg, rgba(24, 18, 52, 0.45), rgba(10, 8, 22, 0.55)), var(--surface-vellum)',
    backgroundSize: 'auto, 256px 256px',
    backgroundRepeat: 'no-repeat, repeat',
    boxShadow: '0 14px 34px rgba(4, 2, 14, 0.45)',
  },
  pc: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    minWidth: 0,
    height: '100%',
  },
  pcGuest: {
    gap: 10,
  },
  pcHead: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    minWidth: 0,
  },
  pcAvatar: {
    flex: 'none',
    width: 56,
    height: 56,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line-strong)',
    borderRadius: '50%',
    objectFit: 'cover',
    backgroundColor: 'rgba(12, 10, 26, 0.6)',
    boxShadow: '0 0 18px rgba(150, 136, 255, 0.18)',
  },
  pcAvatarGuest: {
    filter: 'grayscale(0.7)',
    opacity: 0.85,
  },
  /** Small crest accent balancing the avatar on the other side of the identity row. */
  pcSigil: {
    flex: 'none',
    marginLeft: 'auto',
    filter: 'drop-shadow(0 0 9px rgba(150, 136, 255, 0.45))',
    opacity: 0.9,
  },
  pcId: {
    minWidth: 0,
  },
  pcName: {
    fontFamily: 'var(--font-display)',
    fontSize: 'clamp(1.1rem, 1.9vw, 1.35rem)',
    letterSpacing: '.04em',
    color: 'var(--ink)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  pcMeta: {
    fontSize: '.8rem',
    overflowWrap: 'anywhere',
  },
  pcSub: {
    color: 'var(--ink-faint)',
  },
  pcStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 1,
    padding: 4,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '12px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: 'var(--line)',
    overflow: 'hidden',
  },
  pcStat: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
    padding: '9px 12px',
    backgroundColor: '#131022',
    backgroundImage:
      'linear-gradient(180deg, rgba(122, 104, 255, 0.1), rgba(9, 7, 20, 0) 60%), var(--surface-stone)',
    backgroundSize: 'auto, 256px 256px',
    backgroundRepeat: 'no-repeat, repeat',
    '@media (max-width: 620px)': {
      padding: '8px 10px',
    },
  },
  pcStatLabel: {
    fontSize: '.72rem',
    letterSpacing: '.06em',
    color: 'var(--ink-faint)',
  },
  pcStatValue: {
    fontFamily: 'var(--font-mono)',
    fontSize: '1.2rem',
    fontVariantNumeric: 'tabular-nums',
    color: 'var(--gold)',
    '@media (max-width: 620px)': {
      fontSize: '1.1rem',
    },
  },
  pcStatRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 4,
    minWidth: 0,
    flexWrap: 'wrap',
  },
  pcStatUnit: {
    fontSize: '.72rem',
    color: 'var(--ink-faint)',
    whiteSpace: 'nowrap',
  },
  /** Recent match: a quiet section under a hairline, not another nested box. */
  pcRecent: {
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    minWidth: 0,
    paddingTop: 10,
    borderTop: '1px solid var(--line)',
  },
  pcRecentLine: {
    margin: 0,
    color: 'var(--ink-dim)',
  },
  pcNote: {
    margin: 0,
    color: 'var(--ink-faint)',
  },
  pcNoteError: {
    color: '#ffd8de',
  },
  pcActions: { marginTop: 'auto', paddingTop: 4 },
  pcButton: {
    flex: '1 1 120px',
    minHeight: 48,
  },

  /* ------------------------------------------------- tutorial + guide link -- */

  tutorial: {
    margin: 0,
    padding: 'clamp(12px, 1.8vw, 18px)',
  },
  tutorialHead: {
    marginBottom: 8,
  },
  tutorialSteps: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 10,
    margin: 0,
    padding: 0,
    listStyle: 'none',
    counterReset: 'step',
    color: 'var(--ink-dim)',
    '@media (max-width: 860px)': {
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  tutorialStep: {
    position: 'relative',
    margin: 0,
    padding: '32px 14px 12px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '12px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: '#141126',
    backgroundImage:
      'linear-gradient(180deg, rgba(34, 26, 66, 0.35), rgba(12, 9, 26, 0.45)), var(--surface-vellum)',
    backgroundSize: 'auto, 256px 256px',
    backgroundRepeat: 'no-repeat, repeat',
    fontSize: '.86rem',
    lineHeight: 1.6,
    '::before': {
      counterIncrement: 'step',
      content: 'counter(step)',
      position: 'absolute',
      top: 12,
      left: 14,
      width: 18,
      height: 18,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: 'var(--line-strong)',
      borderRadius: '50%',
      color: 'var(--gold)',
      fontFamily: 'var(--font-mono)',
      fontSize: '.7rem',
      lineHeight: '16px',
      textAlign: 'center',
    },
  },
  guideLink: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 10,
    padding: '10px 14px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '12px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: '#151126',
    backgroundImage:
      'linear-gradient(180deg, rgba(40, 30, 76, 0.35), rgba(16, 12, 34, 0.5)), var(--surface-stone)',
    backgroundSize: 'auto, 256px 256px',
    backgroundRepeat: 'no-repeat, repeat',
    color: 'var(--ink)',
    fontWeight: 600,
    textDecoration: 'none',
    transition: 'background 0.18s ease, box-shadow 0.18s ease, color 0.18s ease',
    ':hover': {
      backgroundImage:
        'linear-gradient(180deg, rgba(64, 48, 110, 0.45), rgba(26, 20, 52, 0.55)), var(--surface-stone)',
      boxShadow: '0 0 0 1px rgba(255, 215, 154, 0.35)',
      color: 'var(--gold)',
    },
  },
  guideArrow: {
    flex: 'none',
    fontFamily: 'var(--font-mono)',
    color: 'var(--gold)',
  },

  /* ------------------------------------------------------------ guide page -- */

  guide: {
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
  },
  guideHead: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 18,
    padding: 'clamp(30px, 3.4vw, 44px) clamp(30px, 3.2vw, 48px)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-panel)',
    borderImageSlice: 48,
    borderImageWidth: '26px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: '#130e23',
    backgroundImage:
      'radial-gradient(120% 90% at 10% 0%, rgba(122, 104, 255, 0.26), transparent 60%), var(--surface-leather)',
    backgroundSize: 'auto, 256px 256px',
    backgroundRepeat: 'no-repeat, repeat',
    boxShadow: 'var(--shadow)',
  },
  guideHeadMain: {
    flex: '1 1 380px',
    minWidth: 0,
  },
  guideTitle: {
    margin: '12px 0 8px',
    fontSize: 'clamp(1.8rem, 4.2vw, 2.7rem)',
    letterSpacing: '.1em',
    color: 'var(--ink)',
  },
  guideLead: {
    maxWidth: '44rem',
    margin: '0 0 16px',
    color: 'var(--ink-dim)',
  },
  guideBack: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    flex: 'none',
    padding: '8px 14px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-control)',
    borderImageSlice: 48,
    borderImageWidth: '10px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    backgroundColor: '#191430',
    backgroundImage: 'var(--surface-stone)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
    color: 'var(--ink)',
    fontSize: '.88rem',
    fontWeight: 600,
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    transition: 'box-shadow 0.18s ease, background 0.18s ease, color 0.18s ease',
    ':hover': {
      backgroundImage:
        'linear-gradient(rgba(255, 215, 154, 0.08), rgba(255, 215, 154, 0.08)), var(--surface-stone)',
      backgroundSize: 'auto, 256px 256px',
      backgroundRepeat: 'no-repeat, repeat',
      boxShadow: '0 0 0 1px rgba(255, 215, 154, 0.4)',
      color: 'var(--gold)',
    },
  },
  backArrow: {
    fontFamily: 'var(--font-mono)',
    color: 'var(--gold)',
  },
  guideGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: 16,
  },
  guideSection: {
    margin: 0,
  },
  guideSectionTitle: {
    margin: '0 0 10px',
    fontSize: '1.1rem',
    letterSpacing: '.05em',
  },
  guideStep: {
    marginBottom: '.5em',
  },
  guideFoot: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  guideFootImg: {
    opacity: 0.7,
  },
});
