import * as stylex from '@stylexjs/stylex';

export const ui = stylex.create({
  button: {
    appearance: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 44,
    padding: '9px 20px',
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-control)',
    borderImageSlice: 48,
    borderImageWidth: '12px',
    borderImageRepeat: 'stretch',
    backgroundColor: '#1d1d30',
    backgroundImage:
      'linear-gradient(180deg,rgba(114,106,145,.16),transparent 55%,rgba(0,0,0,.22)),var(--surface-leather)',
    backgroundSize: 'auto,256px 256px',
    backgroundRepeat: 'no-repeat,repeat',
    backgroundBlendMode: 'normal,luminosity',
    boxShadow: {
      default: 'inset 0 0 14px #080a1380,0 3px 7px #0005',
      ':hover:not(:disabled)': 'inset 0 0 18px #c7baea20,0 3px 9px #0006',
    },
    color: { default: 'var(--ink)', ':hover:not(:disabled)': '#fff4da' },
    font: 'inherit',
    fontSize: '.94rem',
    lineHeight: 1.5,
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    opacity: { default: 1, ':disabled': 0.5 },
    transform: { default: 'none', ':active:not(:disabled)': 'translateY(1px)' },
    transition: 'transform 120ms ease, color 160ms ease, box-shadow 160ms ease',
  },
  primary: {
    backgroundColor: '#343149',
    backgroundImage:
      'linear-gradient(180deg,rgba(117,98,167,.4),rgba(54,42,78,.45)),var(--surface-leather)',
    borderImageSource: 'var(--frame-accent)',
    borderImageWidth: '14px',
    color: '#fff0d0',
    fontWeight: 700,
  },
  gold: {
    backgroundColor: '#4a3722',
    backgroundImage:
      'linear-gradient(180deg,rgba(158,119,54,.32),rgba(65,43,26,.4)),var(--surface-vellum)',
    borderImageSource: 'var(--frame-accent)',
    borderImageWidth: '14px',
    color: '#ffe3ad',
    fontWeight: 700,
  },
  ghost: {
    backgroundImage: 'var(--surface-stone)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
    boxShadow: { default: 'none', ':hover:not(:disabled)': 'inset 0 0 16px #c7baea16' },
  },
  danger: {
    backgroundColor: '#3b2028',
    backgroundImage: 'linear-gradient(#57233166,#30151b99),var(--surface-leather)',
    color: '#ffd8de',
  },
  small: { minHeight: 36, padding: '6px 14px', fontSize: '.85rem', borderImageWidth: '10px' },
  block: { width: '100%' },
  hero: { padding: '15px 22px', fontSize: 'clamp(1rem,1.6vw,1.12rem)', letterSpacing: '.04em' },
  quiet: {
    backgroundImage: 'var(--surface-stone)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
  },
  buttonRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  panel: {
    position: 'relative',
    backgroundColor: 'var(--panel)',
    backgroundImage: 'var(--surface-leather)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-panel)',
    borderImageSlice: 48,
    borderImageWidth: '26px',
    borderImageRepeat: 'stretch',
    borderRadius: 0,
    boxShadow: 'var(--shadow)',
    padding: 'clamp(22px,2.8vw,32px)',
    marginBottom: 20,
  },
  panelHead: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  eyebrow: {
    fontSize: '.76rem',
    letterSpacing: '.24em',
    textTransform: 'uppercase',
    color: 'var(--ink-faint)',
  },
  notice: {
    display: 'flex',
    gap: 10,
    padding: '13px 16px',
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '12px',
    borderImageRepeat: 'stretch',
    backgroundColor: '#11151f',
    backgroundImage: 'var(--surface-stone)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
    fontSize: '.88rem',
    color: 'var(--ink-dim)',
    marginBottom: 14,
  },
  noticeIcon: { flex: 'none', fontSize: '1.05em', lineHeight: 'inherit' },
  field: { display: 'block', marginBottom: 14 },
  label: { display: 'block', marginBottom: 6, fontSize: '.88rem', color: 'var(--ink-dim)' },
  input: {
    width: '100%',
    padding: '9px 13px',
    minHeight: 44,
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '10px',
    borderImageRepeat: 'stretch',
    backgroundColor: '#0b0e17',
    backgroundImage: 'linear-gradient(#06091266,#06091266),var(--surface-stone)',
    backgroundSize: 'auto,256px 256px',
    backgroundRepeat: 'no-repeat,repeat',
    color: 'var(--ink)',
    font: 'inherit',
    lineHeight: 1.5,
    transition: 'border-color 140ms ease, box-shadow 140ms ease',
    borderColor: { default: 'transparent', ':focus': 'transparent' },
    boxShadow: {
      default: 'inset 0 2px 8px #0005',
      ':focus': '0 0 0 2px rgba(178,156,224,.5),inset 0 2px 8px #0005',
    },
  },
  select: {
    appearance: 'none',
    paddingRight: 38,
    cursor: 'pointer',
    borderImageSource: 'var(--frame-control)',
    backgroundImage: 'var(--ornament-chevron),var(--surface-stone)',
    backgroundPosition: 'right 12px center,0 0',
    backgroundSize: '18px 16px,256px 256px',
    backgroundRepeat: 'no-repeat,repeat',
    color: 'var(--gold)',
    fontVariantNumeric: 'tabular-nums',
  },
  hint: { display: 'block', marginTop: 5, fontSize: '.8rem', color: 'var(--ink-faint)' },
  muted: { color: 'var(--ink-dim)' },
  faint: { color: 'var(--ink-faint)' },
  mono: { fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums' },
  title: {
    fontFamily: 'var(--font-display)',
    fontWeight: 600,
    letterSpacing: '.04em',
    margin: '0 0 .5em',
    lineHeight: 1.3,
  },
  stack: { display: 'flex', flexDirection: 'column', gap: 14 },
  srOnly: {
    position: 'absolute',
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: 'hidden',
    clip: 'rect(0,0,0,0)',
    whiteSpace: 'nowrap',
    border: 0,
  },
  smallText: { fontSize: '.86rem' },
  chips: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  chip: {
    padding: '8px 15px',
    minHeight: 40,
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '10px',
    borderImageRepeat: 'stretch',
    backgroundColor: '#171825',
    backgroundImage: 'var(--surface-stone)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
    color: 'var(--ink-dim)',
    font: 'inherit',
    fontSize: '.86rem',
    cursor: 'pointer',
  },
  chipSelected: {
    backgroundImage: 'linear-gradient(#a67c3426,#a67c3426),var(--surface-leather)',
    backgroundSize: 'auto,256px 256px',
    backgroundRepeat: 'no-repeat,repeat',
    borderImageSource: 'var(--frame-accent)',
    borderImageWidth: '12px',
    color: '#ffe3ad',
  },
  steps: { margin: 0, paddingLeft: '1.15em', color: 'var(--ink-dim)' },
  keycap: {
    display: 'inline-block',
    minWidth: '1.6em',
    padding: '1px 6px',
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-control)',
    borderImageSlice: 48,
    borderImageWidth: '6px',
    borderImageRepeat: 'stretch',
    backgroundImage: 'var(--surface-stone)',
    backgroundSize: '256px 256px',
    fontFamily: 'var(--font-mono)',
    fontSize: '.82em',
    textAlign: 'center',
    color: 'var(--ink)',
  },
  rule: {
    height: 20,
    border: 0,
    margin: '12px 0',
    backgroundImage: 'var(--ornament-divider)',
    backgroundSize: 'min(100%,320px) 20px',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
  },
  statTiles: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(140px,1fr))',
    gap: 12,
    margin: '4px 0 16px',
  },
  tile: {
    padding: '16px 18px',
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderImageSource: 'var(--frame-inset)',
    borderImageSlice: 48,
    borderImageWidth: '14px',
    borderImageRepeat: 'stretch',
    backgroundColor: '#262122',
    backgroundImage: 'var(--surface-vellum)',
    backgroundSize: '256px 256px',
    backgroundRepeat: 'repeat',
  },
  tileLabel: {
    fontSize: '.76rem',
    letterSpacing: '.14em',
    color: 'var(--ink-faint)',
    textTransform: 'uppercase',
  },
  tileValue: {
    fontFamily: 'var(--font-mono)',
    fontSize: '1.5rem',
    color: 'var(--ink)',
    fontVariantNumeric: 'tabular-nums',
  },
  resultsWrap: { overflowX: 'auto' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '.9rem' },
  th: {
    textAlign: 'left',
    padding: '9px 10px',
    borderBottom: '1px solid var(--line)',
    whiteSpace: 'nowrap',
    fontSize: '.78rem',
    letterSpacing: '.1em',
    textTransform: 'uppercase',
    color: 'var(--ink-faint)',
    fontWeight: 500,
  },
  td: {
    textAlign: 'left',
    padding: '9px 10px',
    borderBottom: '1px solid var(--line)',
    whiteSpace: 'nowrap',
  },
  num: { textAlign: 'right', fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums' },
});
