import * as stylex from '@stylexjs/stylex';

export const ui = stylex.create({
  button: {
    appearance: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '10px 18px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--line-strong)',
    background: { default: 'rgba(38,31,74,.72)', ':hover:not(:disabled)': 'rgba(56,46,108,.85)' },
    color: 'var(--ink)',
    font: 'inherit',
    fontSize: '.94rem',
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    opacity: { default: 1, ':disabled': 0.45 },
    transform: { default: 'none', ':active:not(:disabled)': 'translateY(1px)' },
    transition:
      'transform 120ms ease, background 160ms ease, border-color 160ms ease, box-shadow 160ms ease',
  },
  primary: {
    background: {
      default: 'linear-gradient(135deg,#6d5ae0,#9a6ff0 62%,#c78bf0)',
      ':hover:not(:disabled)': 'linear-gradient(135deg,#7c69f0,#a97ffb 62%,#d79bfb)',
    },
    borderColor: 'rgba(220,200,255,.5)',
    color: '#120c26',
    fontWeight: 700,
  },
  gold: {
    background: 'linear-gradient(135deg,#f0b25f,#ffd79a)',
    borderColor: 'rgba(255,236,200,.6)',
    color: '#2a1c05',
    fontWeight: 700,
  },
  ghost: { background: 'rgba(14,11,30,.6)' },
  danger: {
    borderColor: 'rgba(255,107,125,.55)',
    background: 'rgba(58,18,30,.7)',
    color: '#ffd8de',
  },
  small: { padding: '6px 12px', fontSize: '.85rem' },
  block: { width: '100%' },
  hero: { padding: '15px 22px', fontSize: 'clamp(1rem,1.6vw,1.12rem)', letterSpacing: '.04em' },
  quiet: { background: 'rgba(12,10,24,.55)' },
  buttonRow: { display: 'flex', flexWrap: 'wrap', gap: 10, alignItems: 'center' },
  panel: {
    position: 'relative',
    background: 'var(--panel)',
    border: '1px solid var(--line)',
    borderRadius: 'var(--radius)',
    boxShadow: 'var(--shadow)',
    backdropFilter: 'blur(10px)',
    padding: 'clamp(16px,2.6vw,28px)',
    marginBottom: 20,
  },
  panelHead: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  eyebrow: {
    fontSize: '.76rem',
    letterSpacing: '.24em',
    textTransform: 'uppercase',
    color: 'var(--ink-faint)',
  },
  notice: {
    display: 'flex',
    gap: 10,
    padding: '11px 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--line)',
    background: 'rgba(16,13,34,.72)',
    fontSize: '.88rem',
    color: 'var(--ink-dim)',
    marginBottom: 14,
  },
  noticeIcon: { flex: 'none', fontSize: '1.05em', lineHeight: 'inherit' },
  field: { display: 'block', marginBottom: 14 },
  label: { display: 'block', marginBottom: 6, fontSize: '.88rem', color: 'var(--ink-dim)' },
  input: {
    width: '100%',
    padding: '10px 13px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--line)',
    background: 'rgba(9,7,20,.72)',
    color: 'var(--ink)',
    font: 'inherit',
    transition: 'border-color 140ms ease, box-shadow 140ms ease',
    borderColor: { default: 'var(--line)', ':focus': 'var(--arcane)' },
    boxShadow: { default: 'none', ':focus': '0 0 0 3px rgba(140,122,255,.18)' },
  },
  hint: { display: 'block', marginTop: 5, fontSize: '.8rem', color: 'var(--ink-faint)' },
  muted: { color: 'var(--ink-dim)' },
  faint: { color: 'var(--ink-faint)' },
  mono: { fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums' },
  title: {
    fontFamily: 'var(--font-display)',
    fontWeight: 600,
    letterSpacing: '.04em',
    margin: '0 0 .5em',
    lineHeight: 1.3,
  },
  stack: { display: 'flex', flexDirection: 'column', gap: 14 },
  srOnly: {
    position: 'absolute',
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: 'hidden',
    clip: 'rect(0,0,0,0)',
    whiteSpace: 'nowrap',
    border: 0,
  },
  smallText: { fontSize: '.86rem' },
  chips: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  chip: {
    padding: '7px 13px',
    borderRadius: 999,
    border: '1px solid var(--line)',
    background: 'rgba(24,19,48,.7)',
    color: 'var(--ink-dim)',
    font: 'inherit',
    fontSize: '.86rem',
    cursor: 'pointer',
  },
  chipSelected: {
    background: 'linear-gradient(135deg,#4b3ca6,#7b5ad6)',
    borderColor: 'rgba(214,196,255,.55)',
    color: '#fff',
  },
  steps: { margin: 0, paddingLeft: '1.15em', color: 'var(--ink-dim)' },
  keycap: {
    display: 'inline-block',
    minWidth: '1.6em',
    padding: '1px 6px',
    borderRadius: 6,
    border: '1px solid var(--line-strong)',
    background: 'rgba(60,50,110,.5)',
    fontFamily: 'var(--font-mono)',
    fontSize: '.82em',
    textAlign: 'center',
    color: 'var(--ink)',
  },
  rule: {
    height: 1,
    border: 0,
    margin: '16px 0',
    background: 'linear-gradient(90deg,transparent,var(--line-strong),transparent)',
  },
  statTiles: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(140px,1fr))',
    gap: 12,
    margin: '4px 0 16px',
  },
  tile: {
    padding: '13px 15px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--line)',
    background: 'rgba(16,13,34,.72)',
  },
  tileLabel: {
    fontSize: '.76rem',
    letterSpacing: '.14em',
    color: 'var(--ink-faint)',
    textTransform: 'uppercase',
  },
  tileValue: {
    fontFamily: 'var(--font-mono)',
    fontSize: '1.5rem',
    color: 'var(--ink)',
    fontVariantNumeric: 'tabular-nums',
  },
  resultsWrap: { overflowX: 'auto' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '.9rem' },
  th: {
    textAlign: 'left',
    padding: '9px 10px',
    borderBottom: '1px solid var(--line)',
    whiteSpace: 'nowrap',
    fontSize: '.78rem',
    letterSpacing: '.1em',
    textTransform: 'uppercase',
    color: 'var(--ink-faint)',
    fontWeight: 500,
  },
  td: {
    textAlign: 'left',
    padding: '9px 10px',
    borderBottom: '1px solid var(--line)',
    whiteSpace: 'nowrap',
  },
  num: { textAlign: 'right', fontFamily: 'var(--font-mono)', fontVariantNumeric: 'tabular-nums' },
});
