import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  seats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 13,
    margin: '8px 0 4px',
    '@media (max-width: 560px)': { gridTemplateColumns: '1fr' },
  },
  seat: {
    display: 'flex',
    gap: 12,
    alignItems: 'center',
    padding: 12,
    borderRadius: 'var(--radius-sm)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    backgroundColor: 'rgba(18, 14, 38, .72)',
    minHeight: 96,
    '@media (max-width: 560px)': { minHeight: 0 },
  },
  seatEmpty: {
    borderStyle: 'dashed',
    color: 'var(--ink-faint)',
    justifyContent: 'center',
    textAlign: 'center',
  },
  seatSelf: { borderColor: 'var(--line-strong)', backgroundColor: 'rgba(40, 32, 82, .6)' },
  seatOffline: { opacity: 0.6 },
  seatAvatar: {
    flex: 'none',
    width: 56,
    height: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line-strong)',
    objectFit: 'cover',
    backgroundColor: '#0d0a1c',
  },
  seatBody: { minWidth: 0 },
  seatName: {
    fontWeight: 600,
    color: 'var(--ink)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  seatMeta: { fontSize: '.79rem', color: 'var(--ink-faint)' },
  seatBadges: { display: 'flex', flexWrap: 'wrap', gap: 5, marginTop: 6 },
  badge: {
    fontSize: '.72rem',
    paddingTop: 2,
    paddingRight: 8,
    paddingBottom: 2,
    paddingLeft: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    color: 'var(--ink-dim)',
  },
  badgeHost: { borderColor: 'rgba(255, 215, 154, .5)', color: 'var(--gold)' },
  badgeReady: { borderColor: 'rgba(100, 230, 176, .5)', color: 'var(--good)' },
  badgeOffline: { borderColor: 'rgba(255, 107, 125, .45)', color: 'var(--danger)' },
  metaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 18,
    margin: '6px 0 2px',
    fontSize: '.88rem',
    color: 'var(--ink-dim)',
  },
  metaValue: { color: 'var(--ink)', fontWeight: 600 },
  invite: { display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  inviteInput: {
    flex: '1 1 260px',
    fontFamily: 'var(--font-mono)',
    fontSize: '.84rem',
  },
  actions: { marginTop: 14 },
});
