/**
 * Binding surface for every Worker module. `Cloudflare.Env` is generated by
 * `bun run cf:types` from wrangler.jsonc; the DeepSeek key is a secret and therefore
 * declared here instead of in the config file.
 */
export type Env = Cloudflare.Env & {
  DEEPSEEK_API_KEY?: string;
};
